name: Python application

on:
  push:
    branches:
      - "main"
    paths:
      - "API/main.py"
      - ".github/workflows/*.yml"
      - "Model/efficientnet_fpn_model_best_iou_diceloss.keras"
  pull_request:
    branches:
      - "main"
    paths:
      - "API/main.py"
      - ".github/workflows/*.yml"
      - "Model/efficientnet_fpn_model_best_iou_diceloss.keras"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest fastapi httpx Pillow numpy==1.23.5 scipy==1.10.1 tensorflow segmentation-models
        if [ -f API/requirements.txt ]; then pip install --no-cache-dir -r API/requirements.txt; fi
        echo "üîç V√©rification des packages install√©s :"
        pip list

    - name: Verify file existence
      run: |
        if [ ! -f "Model/efficientnet_fpn_model_best_iou_diceloss.keras" ]; then
          echo "Mod√®le introuvable : Model/efficientnet_fpn_model_best_iou_diceloss.keras"
          exit 1
        fi

    - name: Ensure API package is recognized
      run: |
        touch API/__init__.py

    - name: Set PYTHONPATH
      run: |
        echo "Setting PYTHONPATH"
        export PYTHONPATH=$PYTHONPATH:/home/runner/work/voiture-autonome/voiture-autonome/API

    - name: Test with pytest
      run: |
        python -m pytest API/testapi.py
      env:
        PYTHONPATH: /home/runner/work/voiture-autonome/voiture-autonome/API
